version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: qryzo-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: qryzo
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: qryzo-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/qryzo
      - JWT_SECRET=qryzo-jwt-secret-key-2024-development-only
      - PORT=3001
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: qryzo-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mongodb_data: